### ISSUE TITLE
Request Specs/Implementation - Creating resources

### ISSUE THREAD

**Issue by blasterpal** [blakechambers/matterhorn#13]
Using JSON API Spec as guide from sections http://jsonapi.org/format/#crud-creating to http://jsonapi.org/format/#crud-creating-responses-other

* [x] - ```POST /posts``` 
* [x] - Nested resource creation

```
POST /posts
{
    "title": "Ember Hamster",
    "body" : "blah blah 111",
      "author": 
        { "id": "9" }
      }
    }
}
```

* [x] - The response MUST include a Location header identifying the location of the newly created resource. - just return self.link. Timebox on multi-create and see what happens.

* [x] Errors http://jsonapi.org/format/#errors & Matterhorn errors as specified athttps://github.com/blakechambers/matterhorn/blob/master/ROADMAP.md

**Comment by blakechambers** [comment]
> Create with links provided as well for setting up relationships on new resource. (ignoring type and data for now)

What exactly does this mean?

**Comment by blasterpal** [comment]
It means CREATING relations via JSON API spec using `links` and `linkage`:`id` instead of standard Rails nested attributes http://jsonapi.org/format/#crud-creating
