### ISSUE TITLE
JSON Spec Implementation Questions and Differentations

### ISSUE THREAD

**Issue by blasterpal** [blakechambers/matterhorn#14]
* Do we wish to strictly require HTTP ```Accept``` of ```application/vnd.api+json```?

**Comment by blakechambers** [comment]
> Support http://jsonapi.org/extensions/bulk/#creating-multiple-resources

https://github.com/blakechambers/matterhorn/commit/f76a5d524857a8c1997bec8b55901975ca8325fa#diff-38574c080d4e2eb38c49b86e6588ad98R61

I'm going to close this as most other questions should be addressed in the [roadmap](https://github.com/blakechambers/matterhorn/blob/master/ROADMAP.md).
