### ISSUE TITLE
Support for top level data 

### ISSUE THREAD

**Issue by blakechambers** [blakechambers/matterhorn#16]
We should support using the top level `data` key and `type` for our JSON as described [in the spec](http://jsonapi.org/format/#document-structure-top-level).  Currently we're using "_id" and "_type".

**Comment by blasterpal** [comment]
In the interest of speed and not breaking what's currently there. Leaving the top level `_id` alone and not changing to `id` per the actual JSON Api spec. We can revisit this before going beta.
