### ISSUE TITLE
Support singleton resources

### ISSUE THREAD

**Issue by blakechambers** [blakechambers/matterhorn#20]
See: https://github.com/josevalim/inherited_resources#singletons

Currently the actions generated for controllers are limited to generating
["resources-style"][resources] routes.  Matterhorn should also support the
addition of [resource][resource] routing and actions.

We should create a concern, `Matterhorn::Resource` and `resource!`, to handle 
the action generation.  The resource method should set the `default singleton: true` configuration so the url_helpers generate the correct paths.

[resource]: http://api.rubyonrails.org/v2.3.8/classes/ActionController/Resources.html#M000310
[resources]: http://api.rubyonrails.org/v2.3.8/classes/ActionController/Resources.html#M000309

**Comment by blasterpal** [comment]
Currently this is *mostly* working although a non-nested route like this:

```
Rails.application.routes.draw do
  resources :posts do
    resource :topic
  end
  # HACK nested singleto links barf without
  resource  :topic

end
```

 is REQUIRED else this exception is raised: 

```
  1) show singleton with_request "GET /#{collection_name}/:id/topic.json" should return nested resource scoped to parent
     Failure/Error: perform_request!
     NoMethodError:
       undefined method `topic_url' for #<Matterhorn::Serialization::UrlBuilder:0x007fdacb159598>
     # ./lib/matterhorn/serialization.rb:119:in `url_for'
     # ./lib/matterhorn/serialization.rb:46:in `links'
     # (eval):5:in `_fast_attributes'
     # ./lib/matterhorn/serialization/scoped_resource_serializer.rb:21:in `_serialized_object'
     # ./lib/matterhorn/serialization/scoped.rb:30:in `serialized_object'
     # ./lib/matterhorn/serialization/scoped.rb:40:in `serializable_hash'
     # ./lib/matterhorn/serialization/scoped_resource_serializer.rb:17:in `serializable_hash'
     # ./lib/matterhorn/serialization/scoped.rb:49:in `as_json'
     # ./lib/matterhorn/responder.rb:13:in `default_render'
     # ./lib/matterhorn/resource.rb:114:in `block in show'
     # ./lib/matterhorn/resource_helpers.rb:121:in `with_scope'
     # ./lib/matterhorn/resource.rb:113:in `show'
     # ./spec/resources_api/singleton/show_spec.rb:26:in `block (3 levels) in <top (required)>'
```

**Comment by blakechambers** [comment]
I think I discussed this some with @Nakort.  Here's what I'm thinking:

Generally speaking, keeping models decoupled from controllers views is a generally accepted part of MVC design.  There are some exceptions to that even in standard rails application design.  An example of that is having a model method `to_param` which influences the way that the models urls are constructed in controllers and views.

Given your example: 

```ruby
Rails.application.routes.draw do
  resources :posts do
    resource :topic
  end

  resource  :topic
end
```

In the case above, topics can be both represented nested under posts (e.g. `post_topic_url`) or as a top level url (e.g. `topic_url`).  During serialization the code isn't sure which url is correct.

I think theres a good use case for creating an instance method on the topic that is called when building the urls out.  

If a model responds_to `matterhorn_url_options`, then it should call that method and use the returned array of items to construct a url.

Now, returning to the above example.  Assuming the above paths:

```ruby
# app/models/topic.rb
class Topic
  
  def matterhorn_url_options
    [post_id, self]
  end
  
end
```

This would create links and templates to the nested version.  However, if the method was undefined, it would default to `[topic]`, which would create a route to the `topic_url`.
