### ISSUE TITLE
Augment serial-spec for JSON Api or create better matchers for JSON API in Matterhorn

### ISSUE THREAD

**Issue by blasterpal** [blakechambers/matterhorn#38]
I can't recall if this was discussed @blakechambers . But we need to write some matchers in Matterhorn for all the :links, :includes, :linkages,etc if serial-spec is not meant to address JSON API spec directly.

Was the intent to add more functionality to serial-spec?

/cc @Nakort

**Comment by blakechambers** [comment]
Any matchers specific to json api should be housed in this gem.  Serial-spec is just intended to be a toolkit for testing any api using rspec.

There should be good uses for custom matchers for things like links, but I'm assuming those will just come out of refactoring and code cleanup organically–no need for an action item for those at this time.
