### ISSUE TITLE
Refactor strong parameters and methods in resources and how should we?

### ISSUE THREAD

**Issue by blasterpal** [blakechambers/matterhorn#43]
There are a lot of methods and some that likely are redundant. However, willy-nilly changing breaks gem. 

So how do we actually want to manage strong parameters, with our own DSL, using `permitted _params` from Inherited Resources, using vanilla `permit`?

**Comment by blasterpal** [comment]
I cleaned out of a lot of similar and unused methods (many I created on my first pass working with code) here: https://github.com/blakechambers/matterhorn/pull/44 I've focused on using `permitted_params` in the actions for now, but this is still a viable topic after other review the code a little in `ResourcesHelper` and `Resources` (`Resource` as well).

**Comment by blakechambers** [comment]
I think this is closable.  Using `permitted_params` is fine.  It's possible that in the future it would make sense to split those into resource and collection params (as collections provide some other things like ordering, filters).  However, permitted_params is fine for current version.
