### ISSUE TITLE
BaseSerializer "type" should be plural

### ISSUE THREAD

**Issue by blakechambers** [blakechambers/matterhorn#64]
Strictly test "type" field always returns a pluralized name.  Currently BaseSerializer returns type as a singular either sometimes or all the time.

Types in links are already pluralized, so we should just ensure that type is pluralized across the board.

**Comment by blasterpal** [comment]
Working on this.

**Comment by blasterpal** [comment]
See PR: https://github.com/blakechambers/matterhorn/pull/71
